import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { nativeImage } from 'electron';
import type { ThumbnailProvider, ThumbnailRequest, ThumbnailResult } from './thumbnailer.ts';

// The real thumbnail provider (spec 22.4). Decodes and downscales with Electron's built-in
// `nativeImage` — no native image-library dependency — and caches the JPEG result on disk
// keyed by the immutable remote version id and target size, so repeat requests (grid
// re-scroll, re-open) are a single file read. This file is the only image code that imports
// Electron; it is constructed by the main process and passed to the backend, never imported
// by the electron-free control server.
//
// `nativeImage.createFromPath` returns an empty image for a format Chromium cannot decode
// (some HEIC/HEIF/WebP on some platforms); the provider returns null there so the route
// falls back to the original bytes.

const THUMBNAIL_JPEG_QUALITY = 72;

export function createElectronThumbnailer(cacheDir: string): ThumbnailProvider {
  return {
    async getThumbnail({
      absolutePath,
      versionId,
      maxSize,
    }: ThumbnailRequest): Promise<ThumbnailResult | null> {
      const cachePath = join(cacheDir, `${versionId}_${maxSize}.jpg`);

      try {
        return { body: await readFile(cachePath), contentType: 'image/jpeg' };
      } catch {
        // Cache miss — generate below.
      }

      const image = nativeImage.createFromPath(absolutePath);
      if (image.isEmpty()) return null;

      const { width, height } = image.getSize();
      const longest = Math.max(width, height);
      // resize() preserves aspect ratio when only one dimension is given; bound the longer
      // edge so portrait and landscape both cap at maxSize.
      const scaled =
        longest > maxSize
          ? image.resize(width >= height ? { width: maxSize } : { height: maxSize })
          : image;
      const body = scaled.toJPEG(THUMBNAIL_JPEG_QUALITY);

      try {
        await mkdir(cacheDir, { recursive: true });
        await writeFile(cachePath, body);
      } catch {
        // A cache-write failure is non-fatal — still serve the freshly generated bytes.
      }

      return { body, contentType: 'image/jpeg' };
    },
  };
}
